//! This code was AUTOGENERATED using the codoma library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codoma to update it.
//!
//! <https://github.com/codoma-idl/codoma>
//!

pub mod accounts;
pub mod errors;
pub mod instructions;
pub mod programs;
pub mod shared;
pub mod types;

pub(crate) use programs::*;
