//! This code was AUTOGENERATED using the codoma library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codoma to update it.
//!
//! <https://github.com/codoma-idl/codoma>
//!

use trezoa_program::{pubkey, pubkey::Pubkey};

/// `trezoa_record_service` program ID.
pub const TREZOA_RECORD_SERVICE_ID: Pubkey = pubkey!("srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa");
