//! This code was AUTOGENERATED using the codoma library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codoma to update it.
//!
//! <https://github.com/codoma-idl/codoma>
//!

#[cfg(feature = "fetch")]
#[derive(Debug, Clone)]
pub struct DecodedAccount<T> {
    pub address: trezoa_program::pubkey::Pubkey,
    pub account: trezoa_sdk::account::Account,
    pub data: T,
}

#[cfg(feature = "fetch")]
#[derive(Debug, Clone)]
pub enum MaybeAccount<T> {
    Exists(DecodedAccount<T>),
    NotFound(trezoa_program::pubkey::Pubkey),
}
