/**
 * This code was AUTOGENERATED using the codoma library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codoma to update it.
 *
 * @see https://github.com/trzledgerfoundation-idl/codoma
 */

import {
  ClusterFilter,
  Context,
  Program,
  PublicKey,
} from '@trezoaplex-foundation/umi';
import {
  getTrezoaRecordServiceErrorFromCode,
  getTrezoaRecordServiceErrorFromName,
} from '../errors';

export const TREZOA_RECORD_SERVICE_PROGRAM_ID =
  'srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa' as PublicKey<'srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa'>;

export function createTrezoaRecordServiceProgram(): Program {
  return {
    name: 'trezoaRecordService',
    publicKey: TREZOA_RECORD_SERVICE_PROGRAM_ID,
    getErrorFromCode(code: number, cause?: Error) {
      return getTrezoaRecordServiceErrorFromCode(code, this, cause);
    },
    getErrorFromName(name: string, cause?: Error) {
      return getTrezoaRecordServiceErrorFromName(name, this, cause);
    },
    isOnCluster() {
      return true;
    },
  };
}

export function getTrezoaRecordServiceProgram<T extends Program = Program>(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): T {
  return context.programs.get<T>('trezoaRecordService', clusterFilter);
}

export function getTrezoaRecordServiceProgramId(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): PublicKey {
  return context.programs.getPublicKey(
    'trezoaRecordService',
    TREZOA_RECORD_SERVICE_PROGRAM_ID,
    clusterFilter
  );
}
