//! This code was AUTOGENERATED using the codoma library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codoma to update it.
//!
//! <https://github.com/trzledgerfoundation-idl/codoma>
//!

use crate::types::Metadata;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use kaigan::types::U8PrefixVec;

/// Accounts.
#[derive(Debug)]
pub struct CreateRecordTokenizable {
    /// Owner of the new record
    pub owner: trezoa_program::pubkey::Pubkey,
    /// Account that will pay for the record account
    pub payer: trezoa_program::pubkey::Pubkey,
    /// Class account for the record to be created
    pub class: trezoa_program::pubkey::Pubkey,
    /// Record account to be created
    pub record: trezoa_program::pubkey::Pubkey,
    /// System Program used to create our record account
    pub system_program: trezoa_program::pubkey::Pubkey,
    /// Optional authority for permissioned classes
    pub authority: Option<trezoa_program::pubkey::Pubkey>,
}

impl CreateRecordTokenizable {
    pub fn instruction(
        &self,
        args: CreateRecordTokenizableInstructionArgs,
    ) -> trezoa_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: CreateRecordTokenizableInstructionArgs,
        remaining_accounts: &[trezoa_program::instruction::AccountMeta],
    ) -> trezoa_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(trezoa_program::instruction::AccountMeta::new_readonly(
            self.owner, true,
        ));
        accounts.push(trezoa_program::instruction::AccountMeta::new(
            self.payer, true,
        ));
        accounts.push(trezoa_program::instruction::AccountMeta::new(
            self.class, false,
        ));
        accounts.push(trezoa_program::instruction::AccountMeta::new(
            self.record,
            false,
        ));
        accounts.push(trezoa_program::instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        if let Some(authority) = self.authority {
            accounts.push(trezoa_program::instruction::AccountMeta::new_readonly(
                authority, true,
            ));
        } else {
            accounts.push(trezoa_program::instruction::AccountMeta::new_readonly(
                crate::TREZOA_RECORD_SERVICE_ID,
                false,
            ));
        }
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&CreateRecordTokenizableInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        trezoa_program::instruction::Instruction {
            program_id: crate::TREZOA_RECORD_SERVICE_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateRecordTokenizableInstructionData {
    discriminator: u8,
}

impl CreateRecordTokenizableInstructionData {
    pub fn new() -> Self {
        Self { discriminator: 4 }
    }
}

impl Default for CreateRecordTokenizableInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateRecordTokenizableInstructionArgs {
    pub expiration: i64,
    pub seed: U8PrefixVec<u8>,
    pub metadata: Metadata,
}

/// Instruction builder for `CreateRecordTokenizable`.
///
/// ### Accounts:
///
///   0. `[signer]` owner
///   1. `[writable, signer]` payer
///   2. `[writable]` class
///   3. `[writable]` record
///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
///   5. `[signer, optional]` authority
#[derive(Clone, Debug, Default)]
pub struct CreateRecordTokenizableBuilder {
    owner: Option<trezoa_program::pubkey::Pubkey>,
    payer: Option<trezoa_program::pubkey::Pubkey>,
    class: Option<trezoa_program::pubkey::Pubkey>,
    record: Option<trezoa_program::pubkey::Pubkey>,
    system_program: Option<trezoa_program::pubkey::Pubkey>,
    authority: Option<trezoa_program::pubkey::Pubkey>,
    expiration: Option<i64>,
    seed: Option<U8PrefixVec<u8>>,
    metadata: Option<Metadata>,
    __remaining_accounts: Vec<trezoa_program::instruction::AccountMeta>,
}

impl CreateRecordTokenizableBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Owner of the new record
    #[inline(always)]
    pub fn owner(&mut self, owner: trezoa_program::pubkey::Pubkey) -> &mut Self {
        self.owner = Some(owner);
        self
    }
    /// Account that will pay for the record account
    #[inline(always)]
    pub fn payer(&mut self, payer: trezoa_program::pubkey::Pubkey) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// Class account for the record to be created
    #[inline(always)]
    pub fn class(&mut self, class: trezoa_program::pubkey::Pubkey) -> &mut Self {
        self.class = Some(class);
        self
    }
    /// Record account to be created
    #[inline(always)]
    pub fn record(&mut self, record: trezoa_program::pubkey::Pubkey) -> &mut Self {
        self.record = Some(record);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    /// System Program used to create our record account
    #[inline(always)]
    pub fn system_program(&mut self, system_program: trezoa_program::pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// `[optional account]`
    /// Optional authority for permissioned classes
    #[inline(always)]
    pub fn authority(&mut self, authority: Option<trezoa_program::pubkey::Pubkey>) -> &mut Self {
        self.authority = authority;
        self
    }
    #[inline(always)]
    pub fn expiration(&mut self, expiration: i64) -> &mut Self {
        self.expiration = Some(expiration);
        self
    }
    #[inline(always)]
    pub fn seed(&mut self, seed: U8PrefixVec<u8>) -> &mut Self {
        self.seed = Some(seed);
        self
    }
    #[inline(always)]
    pub fn metadata(&mut self, metadata: Metadata) -> &mut Self {
        self.metadata = Some(metadata);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: trezoa_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[trezoa_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> trezoa_program::instruction::Instruction {
        let accounts = CreateRecordTokenizable {
            owner: self.owner.expect("owner is not set"),
            payer: self.payer.expect("payer is not set"),
            class: self.class.expect("class is not set"),
            record: self.record.expect("record is not set"),
            system_program: self
                .system_program
                .unwrap_or(trezoa_program::pubkey!("11111111111111111111111111111111")),
            authority: self.authority,
        };
        let args = CreateRecordTokenizableInstructionArgs {
            expiration: self.expiration.clone().expect("expiration is not set"),
            seed: self.seed.clone().expect("seed is not set"),
            metadata: self.metadata.clone().expect("metadata is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `create_record_tokenizable` CPI accounts.
pub struct CreateRecordTokenizableCpiAccounts<'a, 'b> {
    /// Owner of the new record
    pub owner: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// Account that will pay for the record account
    pub payer: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// Class account for the record to be created
    pub class: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// Record account to be created
    pub record: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// System Program used to create our record account
    pub system_program: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// Optional authority for permissioned classes
    pub authority: Option<&'b trezoa_program::account_info::AccountInfo<'a>>,
}

/// `create_record_tokenizable` CPI instruction.
pub struct CreateRecordTokenizableCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// Owner of the new record
    pub owner: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// Account that will pay for the record account
    pub payer: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// Class account for the record to be created
    pub class: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// Record account to be created
    pub record: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// System Program used to create our record account
    pub system_program: &'b trezoa_program::account_info::AccountInfo<'a>,
    /// Optional authority for permissioned classes
    pub authority: Option<&'b trezoa_program::account_info::AccountInfo<'a>>,
    /// The arguments for the instruction.
    pub __args: CreateRecordTokenizableInstructionArgs,
}

impl<'a, 'b> CreateRecordTokenizableCpi<'a, 'b> {
    pub fn new(
        program: &'b trezoa_program::account_info::AccountInfo<'a>,
        accounts: CreateRecordTokenizableCpiAccounts<'a, 'b>,
        args: CreateRecordTokenizableInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            owner: accounts.owner,
            payer: accounts.payer,
            class: accounts.class,
            record: accounts.record,
            system_program: accounts.system_program,
            authority: accounts.authority,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> trezoa_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b trezoa_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> trezoa_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> trezoa_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b trezoa_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> trezoa_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(trezoa_program::instruction::AccountMeta::new_readonly(
            *self.owner.key,
            true,
        ));
        accounts.push(trezoa_program::instruction::AccountMeta::new(
            *self.payer.key,
            true,
        ));
        accounts.push(trezoa_program::instruction::AccountMeta::new(
            *self.class.key,
            false,
        ));
        accounts.push(trezoa_program::instruction::AccountMeta::new(
            *self.record.key,
            false,
        ));
        accounts.push(trezoa_program::instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        if let Some(authority) = self.authority {
            accounts.push(trezoa_program::instruction::AccountMeta::new_readonly(
                *authority.key,
                true,
            ));
        } else {
            accounts.push(trezoa_program::instruction::AccountMeta::new_readonly(
                crate::TREZOA_RECORD_SERVICE_ID,
                false,
            ));
        }
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(trezoa_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&CreateRecordTokenizableInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = trezoa_program::instruction::Instruction {
            program_id: crate::TREZOA_RECORD_SERVICE_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.owner.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.class.clone());
        account_infos.push(self.record.clone());
        account_infos.push(self.system_program.clone());
        if let Some(authority) = self.authority {
            account_infos.push(authority.clone());
        }
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            trezoa_program::program::invoke(&instruction, &account_infos)
        } else {
            trezoa_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CreateRecordTokenizable` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` owner
///   1. `[writable, signer]` payer
///   2. `[writable]` class
///   3. `[writable]` record
///   4. `[]` system_program
///   5. `[signer, optional]` authority
#[derive(Clone, Debug)]
pub struct CreateRecordTokenizableCpiBuilder<'a, 'b> {
    instruction: Box<CreateRecordTokenizableCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CreateRecordTokenizableCpiBuilder<'a, 'b> {
    pub fn new(program: &'b trezoa_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CreateRecordTokenizableCpiBuilderInstruction {
            __program: program,
            owner: None,
            payer: None,
            class: None,
            record: None,
            system_program: None,
            authority: None,
            expiration: None,
            seed: None,
            metadata: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Owner of the new record
    #[inline(always)]
    pub fn owner(&mut self, owner: &'b trezoa_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.owner = Some(owner);
        self
    }
    /// Account that will pay for the record account
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b trezoa_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    /// Class account for the record to be created
    #[inline(always)]
    pub fn class(&mut self, class: &'b trezoa_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.class = Some(class);
        self
    }
    /// Record account to be created
    #[inline(always)]
    pub fn record(
        &mut self,
        record: &'b trezoa_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.record = Some(record);
        self
    }
    /// System Program used to create our record account
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b trezoa_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    /// `[optional account]`
    /// Optional authority for permissioned classes
    #[inline(always)]
    pub fn authority(
        &mut self,
        authority: Option<&'b trezoa_program::account_info::AccountInfo<'a>>,
    ) -> &mut Self {
        self.instruction.authority = authority;
        self
    }
    #[inline(always)]
    pub fn expiration(&mut self, expiration: i64) -> &mut Self {
        self.instruction.expiration = Some(expiration);
        self
    }
    #[inline(always)]
    pub fn seed(&mut self, seed: U8PrefixVec<u8>) -> &mut Self {
        self.instruction.seed = Some(seed);
        self
    }
    #[inline(always)]
    pub fn metadata(&mut self, metadata: Metadata) -> &mut Self {
        self.instruction.metadata = Some(metadata);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b trezoa_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b trezoa_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> trezoa_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> trezoa_program::entrypoint::ProgramResult {
        let args = CreateRecordTokenizableInstructionArgs {
            expiration: self
                .instruction
                .expiration
                .clone()
                .expect("expiration is not set"),
            seed: self.instruction.seed.clone().expect("seed is not set"),
            metadata: self
                .instruction
                .metadata
                .clone()
                .expect("metadata is not set"),
        };
        let instruction = CreateRecordTokenizableCpi {
            __program: self.instruction.__program,

            owner: self.instruction.owner.expect("owner is not set"),

            payer: self.instruction.payer.expect("payer is not set"),

            class: self.instruction.class.expect("class is not set"),

            record: self.instruction.record.expect("record is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),

            authority: self.instruction.authority,
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CreateRecordTokenizableCpiBuilderInstruction<'a, 'b> {
    __program: &'b trezoa_program::account_info::AccountInfo<'a>,
    owner: Option<&'b trezoa_program::account_info::AccountInfo<'a>>,
    payer: Option<&'b trezoa_program::account_info::AccountInfo<'a>>,
    class: Option<&'b trezoa_program::account_info::AccountInfo<'a>>,
    record: Option<&'b trezoa_program::account_info::AccountInfo<'a>>,
    system_program: Option<&'b trezoa_program::account_info::AccountInfo<'a>>,
    authority: Option<&'b trezoa_program::account_info::AccountInfo<'a>>,
    expiration: Option<i64>,
    seed: Option<U8PrefixVec<u8>>,
    metadata: Option<Metadata>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b trezoa_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
