//! This code was AUTOGENERATED using the codoma library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codoma to update it.
//!
//! <https://github.com/trzledgerfoundation-idl/codoma>
//!

use crate::types::AdditionalMetadata;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Token22 Metadata Extension compatible Metadata format
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Metadata {
    pub name: String,
    pub symbol: String,
    pub uri: String,
    pub additional_metadata: Vec<AdditionalMetadata>,
}
