//! This code was AUTOGENERATED using the codoma library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codoma to update it.
//!
//! <https://github.com/trzledgerfoundation-idl/codoma>
//!

pub(crate) mod r#additional_metadata;
pub(crate) mod r#metadata;

pub use self::r#additional_metadata::*;
pub use self::r#metadata::*;
