//! This code was AUTOGENERATED using the codoma library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codoma to update it.
//!
//! <https://github.com/trzledgerfoundation-idl/codoma>
//!

pub(crate) mod r#class;
pub(crate) mod r#record;

pub use self::r#class::*;
pub use self::r#record::*;
