//! This code was AUTOGENERATED using the codoma library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codoma to update it.
//!
//! <https://github.com/codoma-idl/codoma>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use kaigan::types::RemainderVec;
use kaigan::types::U8PrefixVec;
use trezoa_program::pubkey::Pubkey;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Record {
    pub discriminator: u8,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub class: Pubkey,
    pub owner_type: u8,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub owner: Pubkey,
    pub is_frozen: bool,
    pub expiry: i64,
    pub seed: U8PrefixVec<u8>,
    pub data: RemainderVec<u8>,
}

impl Record {
    #[inline(always)]
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        let mut data = data;
        Self::deserialize(&mut data)
    }
}

impl<'a> TryFrom<&trezoa_program::account_info::AccountInfo<'a>> for Record {
    type Error = std::io::Error;

    fn try_from(
        account_info: &trezoa_program::account_info::AccountInfo<'a>,
    ) -> Result<Self, Self::Error> {
        let mut data: &[u8] = &(*account_info.data).borrow();
        Self::deserialize(&mut data)
    }
}

#[cfg(feature = "fetch")]
pub fn fetch_record(
    rpc: &trezoa_client::rpc_client::RpcClient,
    address: &trezoa_program::pubkey::Pubkey,
) -> Result<crate::shared::DecodedAccount<Record>, std::io::Error> {
    let accounts = fetch_all_record(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_record(
    rpc: &trezoa_client::rpc_client::RpcClient,
    addresses: &[trezoa_program::pubkey::Pubkey],
) -> Result<Vec<crate::shared::DecodedAccount<Record>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<Record>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        let account = accounts[i].as_ref().ok_or(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("Account not found: {}", address),
        ))?;
        let data = Record::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::DecodedAccount {
            address,
            account: account.clone(),
            data,
        });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_record(
    rpc: &trezoa_client::rpc_client::RpcClient,
    address: &trezoa_program::pubkey::Pubkey,
) -> Result<crate::shared::MaybeAccount<Record>, std::io::Error> {
    let accounts = fetch_all_maybe_record(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_record(
    rpc: &trezoa_client::rpc_client::RpcClient,
    addresses: &[trezoa_program::pubkey::Pubkey],
) -> Result<Vec<crate::shared::MaybeAccount<Record>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<Record>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        if let Some(account) = accounts[i].as_ref() {
            let data = Record::from_bytes(&account.data)?;
            decoded_accounts.push(crate::shared::MaybeAccount::Exists(
                crate::shared::DecodedAccount {
                    address,
                    account: account.clone(),
                    data,
                },
            ));
        } else {
            decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
        }
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "trezoaanchor")]
impl trezoaanchor_lang::AccountDeserialize for Record {
    fn try_deserialize_unchecked(buf: &mut &[u8]) -> trezoaanchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
    }
}

#[cfg(feature = "trezoaanchor")]
impl trezoaanchor_lang::AccountSerialize for Record {}

#[cfg(feature = "trezoaanchor")]
impl trezoaanchor_lang::Owner for Record {
    fn owner() -> Pubkey {
        crate::TREZOA_RECORD_SERVICE_ID
    }
}

#[cfg(feature = "trezoaanchor-idl-build")]
impl trezoaanchor_lang::IdlBuild for Record {}

#[cfg(feature = "trezoaanchor-idl-build")]
impl trezoaanchor_lang::Discriminator for Record {
    const DISCRIMINATOR: [u8; 8] = [0; 8];
}
